# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  terraformWorkingDir: '$(Build.SourcesDirectory)/env/dev'# Specifies the directory where Terraform configuration files for the DEV environment are located

steps:


#  Checkout GitHub repo

- checkout: self


#  Install Terraform

- task: TerraformInstaller@1
  displayName: "Install Terraform"
  inputs:
    terraformVersion: 'latest'


trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  terraformWorkingDir: '$(Build.SourcesDirectory)/env/dev'

steps:

# Checkout repo
- checkout: self

# Install Terraform
- task: TerraformInstaller@1
  displayName: "Install Terraform"
  inputs:
    terraformVersion: 'latest'

# Terraform Init (reads backend from backend.tf)
- task: TerraformTask@5
  displayName: "Terraform Init - DEV"
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'azure-connection'
    workingDirectory: '$(terraformWorkingDir)'

# Terraform Validate
- script: terraform validate
  workingDirectory: $(terraformWorkingDir)
  displayName: "Terraform Validate"

# Terraform Plan (creates plan file)
- script: terraform plan -out=tfplan
  workingDirectory: $(terraformWorkingDir)
  displayName: "Terraform Plan - DEV"

# Terraform Apply (uses same plan)
- script: terraform apply -auto-approve tfplan
  workingDirectory: $(terraformWorkingDir)
  displayName: "Terraform Apply - DEV"