trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

# Install Terraform
- task: TerraformInstaller@1
  displayName: Install Terraform
  inputs:
    terraformVersion: 'latest'

# Terraform Init (HARDCODED BACKEND HERE)
- task: TerraformTask@5
  displayName: Terraform Init - DEV
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'azure-connection'   # your service connection name
    backendAzureRmResourceGroupName: 'NCPL'
    backendAzureRmStorageAccountName: 'dev1storagecanadacentral'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'dev.terraform.tfstate'
    workingDirectory: '$(Build.SourcesDirectory)/env/dev'

# Terraform Validate
- task: TerraformTask@5
  displayName: Terraform Validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(Build.SourcesDirectory)/env/dev'

# Terraform Plan
- task: TerraformTask@5
  displayName: Terraform Plan - DEV
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'azure-connection'
    workingDirectory: '$(Build.SourcesDirectory)/env/dev'

# Terraform Apply
- task: TerraformTask@5
  displayName: Terraform Apply - DEV
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'azure-connection'
    workingDirectory: '$(Build.SourcesDirectory)/env/dev'