trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  terraformWorkingDir: '$(Build.SourcesDirectory)/env/dev'

steps:
- checkout: self

- task: TerraformInstaller@1
  displayName: Install Terraform
  inputs:
    terraformVersion: 'latest'

# Init (backend comes from backend.tf)
- task: TerraformTask@5
  displayName: Terraform Init - DEV
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'azure-connection'
    workingDirectory: '$(terraformWorkingDir)'

# Validate
- script: terraform validate
  workingDirectory: $(terraformWorkingDir)
  displayName: Terraform Validate

# Plan
- script: terraform plan -out=tfplan
  workingDirectory: $(terraformWorkingDir)
  displayName: Terraform Plan - DEV

# Apply
- script: terraform apply -auto-approve tfplan
  workingDirectory: $(terraformWorkingDir)
  displayName: Terraform Apply - DEV